name: thesis
channels:
  - defaults
dependencies:
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=23.1.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=68.1
  - ipykernel=6.9.1
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.4.4
  - jupyter_core=4.11.2
  - jupyterlab_pygments=0.1.2
  - krb5=1.19.4
  - lerc=3.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.9
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libxslt=1.1.37
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - nbconvert=5.5.0
  - nbformat=5.1.3
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.4.12
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openssl=1.1.1w
  - packaging=23.1
  - pandas=2.1.1
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pymongo=3.12.0
  - pyqt=5.15.7
  - pyrsistent=0.18.0
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=4.6.0
  - qtwebkit=5.212
  - readline=8.2
  - send2trash=1.8.0
  - setuptools=68.0.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - terminado=0.17.1
  - testpath=0.6.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.41.2
  - widgetsnbextension=3.5.2
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - pyqt5-sip==12.11.0
